version: "3.7"

services:
  database_crud:
    platform: linux/x86_64
    image: mysql
    container_name: database_crud
    restart: always
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=crud
    volumes:
      - ./sqldata:/data/mysql
    network_mode: host
  app:
    build: .
    container_name: crud
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host